"""Source registry and Jin10 event router."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class SourceConfig:
    """Configuration for a single data source."""

    source_id: str
    institution: str
    country: str  # "US" | "CN"
    language: str  # "en" | "zh"
    data_category: str
    description: str = ""


# All configured sources
SOURCES: dict[str, SourceConfig] = {
    # --- US Sources ---
    "us_bls_cpi": SourceConfig(
        source_id="us_bls_cpi",
        institution="BLS",
        country="US",
        language="en",
        data_category="inflation",
        description="Consumer Price Index",
    ),
    "us_bls_ppi": SourceConfig(
        source_id="us_bls_ppi",
        institution="BLS",
        country="US",
        language="en",
        data_category="inflation",
        description="Producer Price Index",
    ),
    "us_bls_nfp": SourceConfig(
        source_id="us_bls_nfp",
        institution="BLS",
        country="US",
        language="en",
        data_category="employment",
        description="Employment Situation (Non-Farm Payrolls)",
    ),
    "us_fed_speeches": SourceConfig(
        source_id="us_fed_speeches",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="speeches",
        description="Fed Governor and President Speeches",
    ),
    "us_fed_press_all": SourceConfig(
        source_id="us_fed_press_all",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="press_releases",
        description="Federal Reserve Press Releases (All)",
    ),
    "us_fed_testimony": SourceConfig(
        source_id="us_fed_testimony",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="testimony",
        description="Congressional Testimony",
    ),
    "us_fed_fomc_statement": SourceConfig(
        source_id="us_fed_fomc_statement",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="monetary_policy",
        description="FOMC Statement",
    ),
    "us_fed_fomc_minutes": SourceConfig(
        source_id="us_fed_fomc_minutes",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="monetary_policy",
        description="FOMC Meeting Minutes",
    ),
    "us_fed_beigebook": SourceConfig(
        source_id="us_fed_beigebook",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="economic_conditions",
        description="Beige Book",
    ),
    "us_fed_ip": SourceConfig(
        source_id="us_fed_ip",
        institution="Federal Reserve",
        country="US",
        language="en",
        data_category="industrial_production",
        description="Industrial Production and Capacity Utilization",
    ),
    "us_bea_gdp": SourceConfig(
        source_id="us_bea_gdp",
        institution="BEA",
        country="US",
        language="en",
        data_category="gdp",
        description="Gross Domestic Product",
    ),
    "us_bea_pce": SourceConfig(
        source_id="us_bea_pce",
        institution="BEA",
        country="US",
        language="en",
        data_category="inflation",
        description="Personal Consumption Expenditures",
    ),
    "us_bea_trade": SourceConfig(
        source_id="us_bea_trade",
        institution="BEA",
        country="US",
        language="en",
        data_category="trade",
        description="International Trade in Goods and Services",
    ),
    "us_ism_manufacturing": SourceConfig(
        source_id="us_ism_manufacturing",
        institution="ISM",
        country="US",
        language="en",
        data_category="manufacturing",
        description="ISM Manufacturing PMI",
    ),
    "us_ism_services": SourceConfig(
        source_id="us_ism_services",
        institution="ISM",
        country="US",
        language="en",
        data_category="services",
        description="ISM Services PMI",
    ),
    "us_census_retail": SourceConfig(
        source_id="us_census_retail",
        institution="Census Bureau",
        country="US",
        language="en",
        data_category="consumption",
        description="Advance Monthly Retail Sales",
    ),
    "us_census_housing": SourceConfig(
        source_id="us_census_housing",
        institution="Census Bureau",
        country="US",
        language="en",
        data_category="housing",
        description="New Residential Construction",
    ),
    "us_umich_sentiment": SourceConfig(
        source_id="us_umich_sentiment",
        institution="University of Michigan",
        country="US",
        language="en",
        data_category="consumer_sentiment",
        description="Consumer Sentiment Survey",
    ),
    # --- EU Sources ---
    "ecb_press": SourceConfig(
        source_id="ecb_press",
        institution="European Central Bank",
        country="EU",
        language="en",
        data_category="press_releases",
        description="ECB Press Releases",
    ),
    "ecb_speeches": SourceConfig(
        source_id="ecb_speeches",
        institution="European Central Bank",
        country="EU",
        language="en",
        data_category="speeches",
        description="ECB Speeches",
    ),
    "ecb_working_papers": SourceConfig(
        source_id="ecb_working_papers",
        institution="European Central Bank",
        country="EU",
        language="en",
        data_category="research",
        description="ECB Working Papers",
    ),
    # --- CN Sources ---
    "cn_stats_cpi": SourceConfig(
        source_id="cn_stats_cpi",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="inflation",
        description="居民消费价格指数 (CPI)",
    ),
    "cn_stats_ppi": SourceConfig(
        source_id="cn_stats_ppi",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="inflation",
        description="工业生产者出厂价格指数 (PPI)",
    ),
    "cn_stats_gdp": SourceConfig(
        source_id="cn_stats_gdp",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="gdp",
        description="国内生产总值 (GDP)",
    ),
    "cn_stats_pmi": SourceConfig(
        source_id="cn_stats_pmi",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="manufacturing",
        description="制造业采购经理指数 (PMI)",
    ),
    "cn_stats_industrial": SourceConfig(
        source_id="cn_stats_industrial",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="industrial_production",
        description="规模以上工业增加值",
    ),
    "cn_stats_retail": SourceConfig(
        source_id="cn_stats_retail",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="consumption",
        description="社会消费品零售总额",
    ),
    "cn_stats_fai": SourceConfig(
        source_id="cn_stats_fai",
        institution="国家统计局",
        country="CN",
        language="zh",
        data_category="investment",
        description="固定资产投资",
    ),
    "cn_pboc_monetary": SourceConfig(
        source_id="cn_pboc_monetary",
        institution="中国人民银行",
        country="CN",
        language="zh",
        data_category="monetary",
        description="社会融资规模/M2",
    ),
    "cn_pboc_lpr": SourceConfig(
        source_id="cn_pboc_lpr",
        institution="中国人民银行",
        country="CN",
        language="zh",
        data_category="interest_rate",
        description="贷款市场报价利率 (LPR)",
    ),
    "cn_pboc_mpr": SourceConfig(
        source_id="cn_pboc_mpr",
        institution="中国人民银行",
        country="CN",
        language="zh",
        data_category="monetary_policy",
        description="货币政策执行报告",
    ),
    "cn_caixin_pmi": SourceConfig(
        source_id="cn_caixin_pmi",
        institution="Caixin/S&P Global",
        country="CN",
        language="en",
        data_category="manufacturing",
        description="Caixin Manufacturing PMI",
    ),
    "cn_customs_trade": SourceConfig(
        source_id="cn_customs_trade",
        institution="海关总署",
        country="CN",
        language="zh",
        data_category="trade",
        description="进出口贸易数据",
    ),
    "cn_safe_fx": SourceConfig(
        source_id="cn_safe_fx",
        institution="国家外汇管理局",
        country="CN",
        language="zh",
        data_category="fx_reserves",
        description="外汇储备",
    ),
    "cn_scio_press": SourceConfig(
        source_id="cn_scio_press",
        institution="国务院新闻办",
        country="CN",
        language="zh",
        data_category="press_conference",
        description="国新办新闻发布会",
    ),
}


# Jin10 event name → source_id mapping (for future calendar trigger)
EVENT_ROUTER: dict[str, str] = {
    # US
    "美国CPI年率": "us_bls_cpi",
    "美国CPI月率": "us_bls_cpi",
    "美国核心CPI年率": "us_bls_cpi",
    "美国核心CPI月率": "us_bls_cpi",
    "美国PPI年率": "us_bls_ppi",
    "美国PPI月率": "us_bls_ppi",
    "美国核心PPI年率": "us_bls_ppi",
    "美国核心PPI月率": "us_bls_ppi",
    "美国非农就业人口变动": "us_bls_nfp",
    "美国失业率": "us_bls_nfp",
    "美国联邦基金利率": "us_fed_fomc_statement",
    "美联储利率决议": "us_fed_fomc_statement",
    "FOMC会议纪要": "us_fed_fomc_minutes",
    "美联储褐皮书": "us_fed_beigebook",
    "美国工业产出月率": "us_fed_ip",
    "美国GDP年化季率": "us_bea_gdp",
    "美国实际GDP年化季率": "us_bea_gdp",
    "美国核心PCE物价指数年率": "us_bea_pce",
    "美国核心PCE物价指数月率": "us_bea_pce",
    "美国贸易帐": "us_bea_trade",
    "美国ISM制造业PMI": "us_ism_manufacturing",
    "美国ISM非制造业PMI": "us_ism_services",
    "美国零售销售月率": "us_census_retail",
    "美国新屋开工": "us_census_housing",
    "美国营建许可": "us_census_housing",
    "美国密歇根大学消费者信心指数": "us_umich_sentiment",
    # CN
    "中国CPI年率": "cn_stats_cpi",
    "中国CPI月率": "cn_stats_cpi",
    "中国PPI年率": "cn_stats_ppi",
    "中国GDP年率": "cn_stats_gdp",
    "中国GDP季率": "cn_stats_gdp",
    "中国官方制造业PMI": "cn_stats_pmi",
    "中国官方非制造业PMI": "cn_stats_pmi",
    "中国规模以上工业增加值年率": "cn_stats_industrial",
    "中国社会消费品零售总额年率": "cn_stats_retail",
    "中国城镇固定资产投资年率": "cn_stats_fai",
    "中国M2货币供应年率": "cn_pboc_monetary",
    "中国社会融资规模": "cn_pboc_monetary",
    "中国1年期LPR": "cn_pboc_lpr",
    "中国5年期LPR": "cn_pboc_lpr",
    "中国财新制造业PMI": "cn_caixin_pmi",
    "中国财新服务业PMI": "cn_caixin_pmi",
    "中国贸易帐": "cn_customs_trade",
    "中国出口年率": "cn_customs_trade",
    "中国进口年率": "cn_customs_trade",
    "中国外汇储备": "cn_safe_fx",
}
